compatibility_date = "2022-02-21"
name = "sonicjs"
workers_dev = true
main = "src/server.ts"
compatibility_flags = ["streams_enable_constructors"]

# enter your account id
account_id = "xxx"

# run the `wrangler kv:namespace create sonicjs` command and copy the id below
kv_namespaces = [
  { binding = "KVDATA", id = "xxx" }
]

[env.production]
route = "example.com/*"
kv_namespaces = [
  { binding = "KVDATA", id = "yyy" }
]